#!/bin/bash

# bail out if anything fails
set -e

start_mk () {
  # start minikube 4096/8192
  minikube start --kubernetes-version=v1.13.4\
  --memory=4096\
  --bootstrapper=kubeadm\
  --extra-config=scheduler.address=0.0.0.0\
  --extra-config=controller-manager.address=0.0.0.0
}

start_chaos () {
  kubectl create namespace chaos
  kubectl apply -f kubernetes/chaos/km-configmap.yaml
  kubectl apply -f kubernetes/chaos/km-deployment.yaml
  kubectl apply -f kubernetes/chaos/km-nginx-deployment.yaml
}

cleanup_chaos () {
  kubectl delete -f kubernetes/chaos/km-nginx-deployment.yaml
  kubectl delete -f kubernetes/chaos/km-deployment.yaml
  kubectl delete -f kubernetes/chaos/km-configmap.yaml
  kubectl delete namespace chaos
}

cleanup_mk () {
  # stop minikube
  minikube stop
  minikube delete
  rm -rf ~/.minikube
}

"$@"
